services:
    tariff-fetcher-database:
        container_name: tariff-fetcher-database
        build:
            dockerfile: Dockerfile.database
            context: .
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
        volumes:
            - tariff-fetcher-database-volume:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
    tariff-fetcher-web-api:
        container_name: tariff-fetcher-web-api
        build:
            dockerfile: Dockerfile.web-api
            context: .
        ports:
          - "3000:3000"

volumes:
    tariff-fetcher-database-volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./.database