services:
    wb-tariff-service-database:
        container_name: wb-tariff-service-database
        build:
            dockerfile: Dockerfile.database
            context: .
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
        ports:
            - 35432:5432
    wb-tariff-service-web-api:
        container_name: wb-tariff-service-web-api
        build:
            dockerfile: Dockerfile.web-api
            context: .
        ports:
          - "3000:3000"
        depends_on:
            - wb-tariff-service-database
        restart: always

